services:
  # Message Queue Service - Standalone message broker
  mq-service:
    build:
      context: ../..
      dockerfile: deploy/docker/mq-service.Dockerfile
    image: localhost:5000/mq-service:latest
    container_name: mq-service
    ports:
      - "9090:9090"    # MQ HTTP API
      - "9091:9091"    # MQ gRPC API
    environment:
      - GRPC_PORT=9091
      - HTTP_PORT=9090
      - PERSISTENCE_ENABLED=true
      - PERSISTENCE_DIR=/var/lib/mq
      - MAX_RETRIES=3
      - ACK_TIMEOUT=30s
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - mq-data:/var/lib/mq
    networks:
      - telemetry
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    user: "1000:1000"

  # Telemetry Collector - Core data processing service
  telemetry-collector:
    build:
      context: ../..
      dockerfile: deploy/docker/telemetry-collector.Dockerfile
    image: localhost:5000/telemetry-collector:latest
    container_name: telemetry-collector
    ports:
      - "8080:8080"    # Health endpoint
    environment:
      - WORKERS=4
      - DATA_DIR=/data
      - MAX_ENTRIES=10000
      - HEALTH_PORT=8080
      - MQ_URL=mq-service:9091
      - TOPIC=telemetry
      - CHECKPOINT_ENABLED=true
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - collector-data:/data
    depends_on:
      mq-service:
        condition: service_healthy
    networks:
      - telemetry
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    user: "1000:1000"

  # Telemetry Streamer - Data ingestion service (runs on each node)
  telemetry-streamer:
    build:
      context: ../..
      dockerfile: deploy/docker/telemetry-streamer.Dockerfile
    image: localhost:5000/telemetry-streamer:latest
    container_name: telemetry-streamer
    environment:
      - CSV_FILE=/data/telemetry.csv
      - BROKER_URL=http://mq-service:9090
      - TOPIC=telemetry
      - RATE=1.0
      - WORKERS=1
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      # Mount sample CSV data (create this file first)
      - ./sample-data/telemetry.csv:/data/telemetry.csv:ro
    depends_on:
      mq-service:
        condition: service_healthy
    networks:
      - telemetry
    restart: unless-stopped
    user: "1000:1000"

  # API Gateway - REST API service
  api-gateway:
    build:
      context: ../..
      dockerfile: deploy/docker/api-gateway.Dockerfile
    image: localhost:5000/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8081:8081"    # HTTP API
      - "9093:9093"    # Metrics endpoint
    environment:
      - PORT=8081
      - DATA_DIR=/data
      - COLLECTOR_PORT=8080
      - COLLECTOR_URL=http://telemetry-collector:8080
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - collector-data:/data:ro
    depends_on:
      mq-service:
        condition: service_healthy
      telemetry-collector:
        condition: service_healthy
    networks:
      - telemetry
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    user: "1000:1000"

  # Dashboard - React web interface
  dashboard:
    build:
      context: ../..
      dockerfile: deploy/docker/dashboard.Dockerfile
    image: localhost:5000/dashboard:latest
    container_name: dashboard
    ports:
      - "5173:80"      # Dashboard web interface
    depends_on:
      api-gateway:
        condition: service_healthy
      mq-service:
        condition: service_healthy
      telemetry-collector:
        condition: service_healthy
    networks:
      - telemetry
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  # Persistent storage for collected telemetry data
  collector-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind,uid=1000,gid=1000
  
  # Persistent storage for message queue data
  mq-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mq-data
      o: bind,uid=1000,gid=1000

networks:
  # Internal network for service communication
  telemetry:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16