apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-collector.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "telemetry-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "telemetry-collector.selectorLabels" . | nindent 4 }}