// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/collector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for requests without parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_proto_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_collector_proto_rawDescGZIP(), []int{0}
}

// Response containing a list of GPU IDs
type GPUIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuIds        []string               `protobuf:"bytes,1,rep,name=gpu_ids,json=gpuIds,proto3" json:"gpu_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUIdsResponse) Reset() {
	*x = GPUIdsResponse{}
	mi := &file_internal_proto_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUIdsResponse) ProtoMessage() {}

func (x *GPUIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUIdsResponse.ProtoReflect.Descriptor instead.
func (*GPUIdsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *GPUIdsResponse) GetGpuIds() []string {
	if x != nil {
		return x.GpuIds
	}
	return nil
}

// Request for telemetry data
type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuId         string                 `protobuf:"bytes,1,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // ISO 8601 format
	EndTime       string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // ISO 8601 format
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_internal_proto_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_collector_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryRequest) GetGpuId() string {
	if x != nil {
		return x.GpuId
	}
	return ""
}

func (x *TelemetryRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TelemetryRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TelemetryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TelemetryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response containing telemetry data
type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TelemetryEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_internal_proto_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_collector_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryResponse) GetEntries() []*TelemetryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Telemetry data entry
type TelemetryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601 format
	GpuId         string                 `protobuf:"bytes,2,opt,name=gpu_id,json=gpuId,proto3" json:"gpu_id,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEntry) Reset() {
	*x = TelemetryEntry{}
	mi := &file_internal_proto_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEntry) ProtoMessage() {}

func (x *TelemetryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEntry.ProtoReflect.Descriptor instead.
func (*TelemetryEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_collector_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TelemetryEntry) GetGpuId() string {
	if x != nil {
		return x.GpuId
	}
	return ""
}

func (x *TelemetryEntry) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TelemetryEntry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_internal_proto_collector_proto protoreflect.FileDescriptor

const file_internal_proto_collector_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/collector.proto\x12\x05proto\"\a\n" +
	"\x05Empty\")\n" +
	"\x0eGPUIdsResponse\x12\x17\n" +
	"\agpu_ids\x18\x01 \x03(\tR\x06gpuIds\"\x91\x01\n" +
	"\x10TelemetryRequest\x12\x15\n" +
	"\x06gpu_id\x18\x01 \x01(\tR\x05gpuId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"D\n" +
	"\x11TelemetryResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.proto.TelemetryEntryR\aentries\"s\n" +
	"\x0eTelemetryEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x15\n" +
	"\x06gpu_id\x18\x02 \x01(\tR\x05gpuId\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value2\x8a\x01\n" +
	"\x10CollectorService\x123\n" +
	"\fGetAllGPUIds\x12\f.proto.Empty\x1a\x15.proto.GPUIdsResponse\x12A\n" +
	"\fGetTelemetry\x12\x17.proto.TelemetryRequest\x1a\x18.proto.TelemetryResponseB>Z<github.com/harishb93/telemetry-pipeline/internal/proto;protob\x06proto3"

var (
	file_internal_proto_collector_proto_rawDescOnce sync.Once
	file_internal_proto_collector_proto_rawDescData []byte
)

func file_internal_proto_collector_proto_rawDescGZIP() []byte {
	file_internal_proto_collector_proto_rawDescOnce.Do(func() {
		file_internal_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_collector_proto_rawDesc), len(file_internal_proto_collector_proto_rawDesc)))
	})
	return file_internal_proto_collector_proto_rawDescData
}

var file_internal_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_collector_proto_goTypes = []any{
	(*Empty)(nil),             // 0: proto.Empty
	(*GPUIdsResponse)(nil),    // 1: proto.GPUIdsResponse
	(*TelemetryRequest)(nil),  // 2: proto.TelemetryRequest
	(*TelemetryResponse)(nil), // 3: proto.TelemetryResponse
	(*TelemetryEntry)(nil),    // 4: proto.TelemetryEntry
}
var file_internal_proto_collector_proto_depIdxs = []int32{
	4, // 0: proto.TelemetryResponse.entries:type_name -> proto.TelemetryEntry
	0, // 1: proto.CollectorService.GetAllGPUIds:input_type -> proto.Empty
	2, // 2: proto.CollectorService.GetTelemetry:input_type -> proto.TelemetryRequest
	1, // 3: proto.CollectorService.GetAllGPUIds:output_type -> proto.GPUIdsResponse
	3, // 4: proto.CollectorService.GetTelemetry:output_type -> proto.TelemetryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_collector_proto_init() }
func file_internal_proto_collector_proto_init() {
	if File_internal_proto_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_collector_proto_rawDesc), len(file_internal_proto_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_collector_proto_goTypes,
		DependencyIndexes: file_internal_proto_collector_proto_depIdxs,
		MessageInfos:      file_internal_proto_collector_proto_msgTypes,
	}.Build()
	File_internal_proto_collector_proto = out.File
	file_internal_proto_collector_proto_goTypes = nil
	file_internal_proto_collector_proto_depIdxs = nil
}
