# GPU Telemetry Pipeline - Complete Stack Configuration
# Default values for telemetry-pipeline.

# Global configuration
global:
  namespace: gpu-telemetry
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Override names
nameOverride: ""
fullnameOverride: ""

# Shared resources configuration
shared-resources:
  enabled: true

# Message Queue Service
mq-service:
  enabled: true

# Telemetry Collector
telemetry-collector:
  enabled: true

# Telemetry Streamer (DaemonSet)
telemetry-streamer:
  enabled: true

# API Gateway
api-gateway:
  enabled: true

# Dashboard (Frontend)
dashboard:
  enabled: true
