{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-api-gateway
  labels:
    {{- include "telemetry-pipeline.api-gateway.labels" . | nindent 4 }}
  {{- with .Values.apiGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  {{- if and (eq .Values.apiGateway.service.type "LoadBalancer") .Values.apiGateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.apiGateway.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.apiGateway.service.type "LoadBalancer") .Values.apiGateway.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.apiGateway.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.apiGateway.service.type "ClusterIP") .Values.apiGateway.service.clusterIP }}
  clusterIP: {{ .Values.apiGateway.service.clusterIP }}
  {{- end }}
  {{- if .Values.apiGateway.service.externalIPs }}
  externalIPs:
    {{- range .Values.apiGateway.service.externalIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.apiGateway.service.type "NodePort") (eq .Values.apiGateway.service.type "LoadBalancer")) .Values.apiGateway.service.nodePort }}
      nodePort: {{ .Values.apiGateway.service.nodePort }}
      {{- end }}
    - port: {{ .Values.apiGateway.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
      {{- if and (or (eq .Values.apiGateway.service.type "NodePort") (eq .Values.apiGateway.service.type "LoadBalancer")) .Values.apiGateway.service.metricsNodePort }}
      nodePort: {{ .Values.apiGateway.service.metricsNodePort }}
      {{- end }}
    {{- range .Values.apiGateway.service.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "telemetry-pipeline.api-gateway.selectorLabels" . | nindent 4 }}
{{- end }}