{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-api-gateway
  labels:
    {{- include "telemetry-pipeline.api-gateway.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiGateway.autoscaling.enabled }}
  replicas: {{ .Values.apiGateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "telemetry-pipeline.api-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-gateway-configmap.yaml") . | sha256sum }}
        {{- with .Values.apiGateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "telemetry-pipeline.api-gateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.apiGateway.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "telemetry-pipeline.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiGateway.podSecurityContext | nindent 8 }}
      containers:
        - name: api-gateway
          securityContext:
            {{- toYaml .Values.apiGateway.securityContext | nindent 12 }}
          image: {{ include "telemetry-pipeline.image" .Values.apiGateway.image }}
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          args:
            - -port={{ .Values.apiGateway.port }}
            - -data-dir=/data
            - -collector-port={{ .Values.collector.healthPort }}
            {{- range .Values.apiGateway.extraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.apiGateway.metricsPort | default 9092 }}
              protocol: TCP
          env:
            - name: COLLECTOR_HOST
              value: {{ include "telemetry-pipeline.fullname" . }}-collector
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- with .Values.apiGateway.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
              readOnly: true
            {{- with .Values.apiGateway.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.apiGateway.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apiGateway.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.apiGateway.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.apiGateway.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.apiGateway.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apiGateway.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.apiGateway.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.apiGateway.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "telemetry-pipeline.fullname" . }}-api-gateway-config
        - name: data
          {{- if .Values.collector.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "telemetry-pipeline.fullname" . }}-collector-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.apiGateway.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}