{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-api-gateway-config
  labels:
    {{- include "telemetry-pipeline.api-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: {{ .Values.apiGateway.port }}
    data_dir: "/data"
    collector:
      port: {{ .Values.collector.healthPort }}
      host: {{ include "telemetry-pipeline.fullname" . }}-collector
    cors:
      enabled: {{ .Values.apiGateway.cors.enabled }}
      {{- if .Values.apiGateway.cors.enabled }}
      allowed_origins: {{ .Values.apiGateway.cors.allowedOrigins | toJson }}
      allowed_methods: {{ .Values.apiGateway.cors.allowedMethods | toJson }}
      allowed_headers: {{ .Values.apiGateway.cors.allowedHeaders | toJson }}
      {{- end }}
    {{- if .Values.apiGateway.config }}
    {{- .Values.apiGateway.config | toYaml | nindent 4 }}
    {{- end }}
{{- end }}