{{- if .Values.streamer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-streamer-config
  labels:
    {{- include "telemetry-pipeline.streamer.labels" . | nindent 4 }}
data:
  telemetry.csv: |
    {{- .Values.streamer.csvData | nindent 4 }}
  config.yaml: |
    rate: {{ .Values.streamer.rate }}
    workers: {{ .Values.streamer.workers }}
    broker:
      port: {{ .Values.mq.port }}
      topics: {{ .Values.mq.topics | toJson }}
    {{- if .Values.streamer.config }}
    {{- .Values.streamer.config | toYaml | nindent 4 }}
    {{- end }}
{{- end }}