apiVersion: v1
kind: Service
metadata:
  name: {{ include "mq-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mq-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
      name: admin
    - port: {{ .Values.service.ports.broker }}
      targetPort: broker
      protocol: TCP
      name: broker
  selector:
    {{- include "mq-service.selectorLabels" . | nindent 4 }}